/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package components.transaksi;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Koneksi;
/**
 *
 * @author lumiere
 */
public class FormTransaksi extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTransaksi.class.getName());
    DefaultTableModel table;
    String query;
    Koneksi koneksi = new Koneksi(); //membuat objek dengan nama k
    Connection connect = koneksi.buatKoneksi();
    int hargaBeli;
    int jumlahBeli;
    int totalHarga;

    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(getContentPane());
        setContentPane(scroll);
        setLocationRelativeTo(this);
        String[] data = {"Kode","Nama Barang","Harga Beli","Jumlah","Total Harga"};
        table = new DefaultTableModel(data,0);
        TabelTransaksi.setModel(table);
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InputNomorTransaksi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        InputKodeBarang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        InputNamaBarang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        InputTotalHarga = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        InputHargaBeli = new javax.swing.JTextField();
        ButtonTambah = new javax.swing.JButton();
        ButtonBatal = new javax.swing.JButton();
        ButtonCariBarang = new javax.swing.JButton();
        InputJumlah = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        InputTanggalTransaksi = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        InputKodeSupplier = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        InputNamaSupplier = new javax.swing.JTextField();
        InputKontak = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ButtonCariSuplier = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelTransaksi = new javax.swing.JTable();
        ButtonSimpan = new javax.swing.JButton();
        ButtonCetak = new javax.swing.JButton();
        ButtonTutup = new javax.swing.JButton();
        ButtonRefreshTabel = new javax.swing.JButton();
        ButtonRefreshTabel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Adwaita Sans", 1, 24)); // NOI18N
        jLabel1.setText("INPUT TRANSAKSI PEMBELIAN");

        jLabel3.setText("Nomor Transaksi:");

        jLabel4.setText("Tgl Transaksi:");

        jLabel5.setFont(new java.awt.Font("Adwaita Sans", 1, 14)); // NOI18N
        jLabel5.setText("Data Barang");

        jLabel6.setText("(yyyy-mm-dd)");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Kode Barang:");

        InputKodeBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputKodeBarangActionPerformed(evt);
            }
        });

        jLabel8.setText("Nama Barang:");

        jLabel9.setText("Total Harga:");

        jLabel12.setText("Harga Beli:");

        ButtonTambah.setText("Tambah");
        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahActionPerformed(evt);
            }
        });

        ButtonBatal.setText("Batal");
        ButtonBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonBatalActionPerformed(evt);
            }
        });

        ButtonCariBarang.setText("Cari Barang");
        ButtonCariBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCariBarangActionPerformed(evt);
            }
        });

        InputJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputJumlahActionPerformed(evt);
            }
        });

        jLabel18.setText("Jumlah:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonTambah)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonBatal)
                        .addContainerGap(433, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(InputNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InputHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InputTotalHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(InputJumlah)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(InputKodeBarang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonCariBarang)))
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InputKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCariBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(InputNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(InputHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InputTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonTambah)
                    .addComponent(ButtonBatal))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        InputTanggalTransaksi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("YYYY-MM-DD"))));

        jLabel10.setFont(new java.awt.Font("Adwaita Sans", 1, 14)); // NOI18N
        jLabel10.setText("Data Suplier");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel15.setText("Kode Suplier:");

        InputKodeSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputKodeSupplierActionPerformed(evt);
            }
        });

        jLabel16.setText("Nama Suplier:");

        jLabel17.setText("Kontak:");

        ButtonCariSuplier.setText("Cari Supplier");
        ButtonCariSuplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCariSuplierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InputKontak, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(InputNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(InputKodeSupplier)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ButtonCariSuplier))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(InputKodeSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonCariSuplier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(InputNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(InputKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        TabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TabelTransaksi);

        ButtonSimpan.setText("Simpan");
        ButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSimpanActionPerformed(evt);
            }
        });

        ButtonCetak.setText("Cetak");

        ButtonTutup.setText("Tutup");
        ButtonTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTutupActionPerformed(evt);
            }
        });

        ButtonRefreshTabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N
        ButtonRefreshTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRefreshTabelActionPerformed(evt);
            }
        });

        ButtonRefreshTabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/reload.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonCetak)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonTutup))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ButtonRefreshTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(InputTanggalTransaksi)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel6))
                                            .addComponent(InputNomorTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1))))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ButtonRefreshTabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InputNomorTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(InputTanggalTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(ButtonRefreshTabel, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSimpan)
                    .addComponent(ButtonCetak)
                    .addComponent(ButtonTutup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ButtonRefreshTabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonBatalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonBatalActionPerformed

    private void ButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahActionPerformed
        // TODO add your handling code here:
        String valueKodeBarang = InputNomorTransaksi.getText();
        String valueTotalHarga = InputTotalHarga.getText();
        String valueJumlah = InputJumlah.getText();
        
        if (valueKodeBarang.equals("")) {
            JOptionPane.showMessageDialog(null, "Nomor Transaksi tidak boleh kosong!", "Warning!", JOptionPane.WARNING_MESSAGE);
            InputNomorTransaksi.requestFocus();
            return;
        } else if (valueTotalHarga.equals("")) {
            JOptionPane.showMessageDialog(null, "Total Harga tidak boleh kosong!", "Warning!", JOptionPane.WARNING_MESSAGE);
            InputTotalHarga.requestFocus();
            return;
        } else if (valueJumlah.equals("")) {
            JOptionPane.showMessageDialog(null, "Total Harga tidak boleh kosong!", "Warning!", JOptionPane.WARNING_MESSAGE);
            InputTotalHarga.requestFocus();
            return;
        }
        
        try {
            query = "insert into tabelpembeliandetail values('"+InputNomorTransaksi.getText()+"','"+InputKodeBarang.getText()+"','"+InputJumlah.getText()+"','"+InputTotalHarga.getText()+"')";
            connect.createStatement().executeUpdate(query);
            //JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan");
            bersih();
            tampil();
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(rootPane, "Database Error: " + error.getMessage());
            System.out.println("Database Error: " + error.getMessage());            
        }
    }//GEN-LAST:event_ButtonTambahActionPerformed

    private void ButtonCariBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCariBarangActionPerformed
        // TODO add your handling code here:
        String searchInput = InputKodeBarang.getText().trim();

        if (searchInput.equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan keyword terlebih dahulu!");
            InputKodeBarang.requestFocus();
            return;
        }

        try {
            query = "SELECT * FROM tabelbarang WHERE Kode= '"+InputKodeBarang.getText()+"'";
            Statement st = connect.createStatement();
            ResultSet rs = st.executeQuery(query);
            boolean found = false;
            
            while (rs.next()) {
                found = true;
                InputNamaBarang.setText(rs.getString("NamaBarang"));
                InputHargaBeli.setText(rs.getString("HargaBeli"));
//                InputJumlah.requestFocus();
            }
            
            if (!found) {
                JOptionPane.showMessageDialog(rootPane, "Kode '" + searchInput + "' tidak ditemukan!");
                System.out.println("Kode '" + searchInput + "' tidak ditemukan!");
            }
            
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(rootPane, "Database Error: " + error.getMessage());
            System.out.println("Database Error: " + error.getMessage());
        }    
    }//GEN-LAST:event_ButtonCariBarangActionPerformed

    private void ButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSimpanActionPerformed
        // TODO add your handling code here:
        Object value = InputTanggalTransaksi.getValue();
        if (value == null) {
            JOptionPane.showMessageDialog(rootPane, "Tanggal tidak valid!\nGunakan format yyyy-MM-dd", "Tanggal Tidak Valid", JOptionPane.WARNING_MESSAGE);
            return;
        }
//        Date tgl = (Date) value;
        
        try {
            query = "INSERT INTO tabelpembelian values('"+InputNomorTransaksi.getText()+"','"+InputTanggalTransaksi.getText()+"','"+InputKodeSupplier.getText()+"')";
            connect.createStatement().executeUpdate(query);
            JOptionPane.showMessageDialog(rootPane, "Data berhasil disimpan");
            bersih();
            tampil();
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(rootPane, "Database Error: " + error.getMessage());
            System.out.println("Database Error: " + error.getMessage());
        }
    }//GEN-LAST:event_ButtonSimpanActionPerformed

    private void ButtonCariSuplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCariSuplierActionPerformed
        // TODO add your handling code here:
        String searchInput = InputKodeSupplier.getText().trim();

        if (searchInput.equals("")) {
            JOptionPane.showMessageDialog(null, "Masukkan keyword terlebih dahulu!");
            InputKodeSupplier.requestFocus();
            return;
        }
        
        try {
            query="SELECT * FROM tabelsuplier WHERE KodeSuplier= '"+InputKodeSupplier.getText()+"'";
            Statement st = connect.createStatement();
            ResultSet rs = st.executeQuery(query);
            boolean found = false;
            
            while(rs.next()) {
                found = true;
                InputNamaSupplier.setText(rs.getString("NamaSuplier"));
                InputKontak.setText(rs.getString("Kontak"));
            }
            
            if (!found) {
                JOptionPane.showMessageDialog(rootPane, "Kode Suplier '" + searchInput + "' tidak ditemukan!");
                System.out.println("Kode Suplier '" + searchInput + "' tidak ditemukan!");
            }
        } catch(SQLException error) {
            JOptionPane.showMessageDialog(null,"Data yang Anda cari Tidak dapat Ditemukan: " + error.getMessage());
            System.out.println("Internal Server Error: " + error.getMessage());
        }
    }//GEN-LAST:event_ButtonCariSuplierActionPerformed

    private void InputKodeSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputKodeSupplierActionPerformed
        // TODO add your handling code here:
        ButtonCariSuplier.doClick();
    }//GEN-LAST:event_InputKodeSupplierActionPerformed

    private void InputKodeBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputKodeBarangActionPerformed
        // TODO add your handling code here:
        ButtonCariBarang.doClick();
    }//GEN-LAST:event_InputKodeBarangActionPerformed

    private void InputJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputJumlahActionPerformed
        // TODO add your handling code here:
        hargaBeli=Integer.parseInt(InputHargaBeli.getText());
        jumlahBeli=Integer.parseInt(InputJumlah.getText());
        totalHarga = jumlahBeli * hargaBeli;
        InputTotalHarga.setText(Integer.toString(totalHarga)); 
    }//GEN-LAST:event_InputJumlahActionPerformed

    private void ButtonTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTutupActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonTutupActionPerformed

    private void ButtonRefreshTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRefreshTabelActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil model tabel yang sudah ada
            DefaultTableModel table = (DefaultTableModel) TabelTransaksi.getModel();

            // Hapus semua baris lama
            int row = table.getRowCount();
            for (int i = 0; i < row; i++) {
                table.removeRow(0);
            }

            // Ambil semua data dari tabelbarang
            query = "SELECT tabelbarang.Kode, tabelbarang.NamaBarang, tabelbarang.HargaBeli, tabelpembeliandetail.Jumlah, tabelpembeliandetail.TotalHarga FROM tabelbarang JOIN tabelpembeliandetail ON tabelbarang.Kode = tabelpembeliandetail.KodeBarang WHERE tabelpembeliandetail.NoTransaksi = '"+InputNomorTransaksi.getText()+"'";
            Statement stmt = connect.createStatement();
            ResultSet rs = stmt.executeQuery(query);
            
            // Tambahkan ke JTable
            while (rs.next()) {
                String[] data = {
                    rs.getString("Kode"),
                    rs.getString("NamaBarang"),
                    rs.getString("HargaBeli"),
                    rs.getString("Jumlah"),
                    rs.getString("TotalHarga")
                };
                table.addRow(data);
            }
            
            // Tutup koneksi
            connect.close();
            
            // Opsional: tampilkan pesan sukses
            JOptionPane.showMessageDialog(rootPane, "Tabel berhasil diperbarui!");

        } catch (SQLException error) {
            JOptionPane.showMessageDialog(rootPane, "Gagal memuat data: " + error.getMessage());
            System.out.println("Gagal memuat data: " + error.getMessage());
        }
    }//GEN-LAST:event_ButtonRefreshTabelActionPerformed
    
    private void bersih(){
        InputKodeBarang.setText(null);
        InputNamaBarang.setText(null);
        InputHargaBeli.setText(null);
        InputJumlah.setText(null);
        InputTotalHarga.setText(null);
        InputKodeBarang.requestFocus();
    }
    
    private void tampil() {
        try {
            int row=TabelTransaksi.getRowCount();
            for(int i=0; i<row;i++){
                table.removeRow(0);
            }
            
            query = "SELECT tabelbarang.Kode, tabelbarang.NamaBarang, tabelbarang.HargaBeli, tabelpembeliandetail.Jumlah, tabelpembeliandetail.TotalHarga FROM tabelbarang JOIN tabelpembeliandetail ON tabelbarang.Kode = tabelpembeliandetail.KodeBarang WHERE tabelpembeliandetail.NoTransaksi = '"+InputNomorTransaksi.getText()+"'";
            ResultSet dat= connect.createStatement().executeQuery(query);
            while(dat.next()){
                String[] data={dat.getString(1),dat.getString(2),dat.getString(3),dat.getString(4),dat.getString(5)};
                table.addRow(data);
            }
        } catch (SQLException error) {
            JOptionPane.showMessageDialog(rootPane, "Database Error: " + error.getMessage());
            System.out.println("Database Error: " + error.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FormTransaksi dialog = new FormTransaksi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonBatal;
    private javax.swing.JButton ButtonCariBarang;
    private javax.swing.JButton ButtonCariSuplier;
    private javax.swing.JButton ButtonCetak;
    private javax.swing.JButton ButtonRefreshTabel;
    private javax.swing.JButton ButtonRefreshTabel1;
    private javax.swing.JButton ButtonSimpan;
    private javax.swing.JButton ButtonTambah;
    private javax.swing.JButton ButtonTutup;
    private javax.swing.JTextField InputHargaBeli;
    private javax.swing.JTextField InputJumlah;
    private javax.swing.JTextField InputKodeBarang;
    private javax.swing.JTextField InputKodeSupplier;
    private javax.swing.JTextField InputKontak;
    private javax.swing.JTextField InputNamaBarang;
    private javax.swing.JTextField InputNamaSupplier;
    private javax.swing.JTextField InputNomorTransaksi;
    private javax.swing.JFormattedTextField InputTanggalTransaksi;
    private javax.swing.JTextField InputTotalHarga;
    private javax.swing.JTable TabelTransaksi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
